services:
    backend:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/app/backend
        depends_on:
            - database
            - redis
        container_name: nomadcars-app

    nginx:
        image: nginx:latest
        restart: unless-stopped
        volumes:
            - ./:/app/backend
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "8080:8080"
        depends_on:
            - backend
        container_name: nomadcars-nginx

    database:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres_user
            POSTGRES_PASSWORD: postgres_password
            POSTGRES_DB: postgres_db
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - ./db_data:/var/lib/postgresql/data/pgdata
        command: >
            postgres -c max_connections=1000
                     -c shared_buffers=256MB
                     -c effective_cache_size=768MB
                     -c maintenance_work_mem=64MB
                     -c checkpoint_completion_target=0.7
                     -c wal_buffers=16MB
                     -c default_statistics_target=100
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: unless-stopped
        tty: true
        stdin_open: true
        container_name: nomadcars-database

    redis:
        image: redis:latest
        restart: unless-stopped
        ports:
            - "6379:6379"
        container_name: nomadcars-redis
